name: Build Telegram X Multi-ABI (Android-ready fork)

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_HASH: ${{ secrets.APP_HASH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork Android-ready
        uses: actions/checkout@v4
        with:
          repository: TON_USERNAME/TON_FORK
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate local.properties with Telegram credentials
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
          echo "telegram.api_id=${APP_ID}" >> local.properties
          echo "telegram.api_hash=${APP_HASH}" >> local.properties
          cat local.properties
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_HASH: ${{ secrets.APP_HASH }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config gperf wget unzip perl python3 zlib1g-dev libssl-dev build-essential

      - name: Build OpenSSL for Android
        run: |
          mkdir -p tdlib/openssl
          cd tdlib/openssl
          wget https://www.openssl.org/source/openssl-1.1.1u.tar.gz
          tar xvf openssl-1.1.1u.tar.gz
          cd openssl-1.1.1u
          export ANDROID_NDK=$ANDROID_NDK_HOME
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          ./Configure android-arm -D__ANDROID_API__=24 no-shared no-unit-test
          make -j$(nproc)
          cd ../../../

      - name: Build TDLib for Android
        run: |
          cd tdlib
          mkdir -p build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=armeabi-v7a \
                -DANDROID_PLATFORM=android-24 \
                -DCMAKE_BUILD_TYPE=Release \
                -DOPENSSL_ROOT_DIR=$GITHUB_WORKSPACE/tdlib/openssl/openssl-1.1.1u \
                -DCMAKE_INSTALL_PREFIX:PATH=../install ..
          cmake --build . --target install -j$(nproc)
          cd ../..
          mkdir -p app/tdlib/source
          cp -r tdlib/install/include app/tdlib/source/
          cp -r tdlib/install/lib app/tdlib/source/

      - name: Build release APK(s) for all ABIs
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telegram-x-apks
          path: '**/build/outputs/apk/**/*.apk'
          compression-level: 6
          overwrite: true
