name: Build Telegram X

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_HASH: ${{ secrets.APP_HASH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate local.properties with Telegram credentials
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
          echo "telegram.api_id=${APP_ID}" >> local.properties
          echo "telegram.api_hash=${APP_HASH}" >> local.properties
          cat local.properties
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_HASH: ${{ secrets.APP_HASH }}

      - name: Build release APK(s)
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telegram-x-apks
          path: '**/build/outputs/apk/**/*.apk'
          compression-level: 6
          overwrite: true
